"""add_share_token_to_conversations

Revision ID: 1cbaed26072d
Revises: b7ea8f8fb6fa
Create Date: 2026-07-30 07:59:10.437259

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1cbaed26072d'
down_revision: str | None = 'b7ea8f8fb6fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('conversations', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_share_token'), 'conversations', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_share_token'), table_name='conversations')
    op.drop_column('conversations', 'share_token')
    op.drop_column('conversations', 'is_shared')
    # ### end Alembic commands ###
