"""add document sections

Revision ID: 6e8841c9840a
Revises: 4ba5e583b21b
Create Date: 2026-07-15 10:59:57.079764

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6e8841c9840a'
down_revision: str | None = '4ba5e583b21b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sections',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_sections_document_id', 'document_sections', ['document_id', 'section_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_sections_document_id', table_name='document_sections')
    op.drop_table('document_sections')
    # ### end Alembic commands ###
